Compte:
   definition:
     fields:
       _id: { }
       _rev: { }
       type: { }
       identifiant: { }
       civilite: { }
       prenom: { }
       nom: { }
       fonction: { }
       commentaire: { }
       id_societe: { }
       adresse: { }       
       adresse_complementaire: { }
       code_postal: { }
       commune: { }
       type: { }
       cedex: {  }
       pays: {  }
       email: {  }
       telephone_perso: {  }
       telephone_bureau: {  }
       telephone_mobile: {  }
       fax: {  }
       nom_a_afficher: {  }
       tags:
         type: collection
         definition:
           fields:
             '*': { }
         